import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { OptionSnapshot, OptionsSeries } from "../types";
import { PanelHeader } from "./Charts";

type SortKey = "ticker" | "asOf" | "spot" | "atmIv30D" | "realizedVolatility20D" | "impliedRealizedSpread" | "skew30D" | "expectedMove30D";
const columns: Array<[SortKey, string]> = [["ticker", "Ticker"], ["asOf", "As of"], ["spot", "Spot"], ["atmIv30D", "ATM IV"], ["realizedVolatility20D", "20D realized"], ["impliedRealizedSpread", "IV - realized"], ["skew30D", "Put-call skew"], ["expectedMove30D", "Model move"]];

export function OptionsView({ series }: { series?: OptionsSeries }) {
  const snapshots = series?.snapshots ?? [];
  const [ticker, setTicker] = useState("SPY");
  const [sortKey, setSortKey] = useState<SortKey>("impliedRealizedSpread");
  const [direction, setDirection] = useState<"asc" | "desc">("desc");
  const active = snapshots.find((row) => row.ticker === ticker) ?? snapshots[0];
  const sorted = useMemo(() => sortRows(snapshots, sortKey, direction), [direction, snapshots, sortKey]);
  const terms = (active?.terms ?? []).map((term) => ({ ...term, atm: percentIV(term.atmIv), put: percentIV(term.putWingIv), call: percentIV(term.callWingIv) }));
  function sort(next: SortKey) { if (next === sortKey) setDirection((value) => value === "asc" ? "desc" : "asc"); else { setSortKey(next); setDirection(next === "ticker" ? "asc" : "desc"); } }
  if (!active) return <div className="loading">Options snapshot pending outside market hours</div>;

  return <>
    <section className="options-toolbar"><label>Underlying<select value={active.ticker} onChange={(event) => setTicker(event.target.value)}>{snapshots.map((row) => <option key={row.ticker}>{row.ticker}</option>)}</select></label><div><span>Observation</span><strong>{active.asOf ?? series?.asOf ?? "--"}</strong></div><div><span>Coverage</span><strong>{snapshots.length} underlyings</strong></div></section>
    <section className="signal-strip"><div><span>30D ATM implied</span><strong>{formatIV(active.atmIv30D)}</strong><small>Mid-market volatility</small></div><div><span>20D realized</span><strong>{formatPct(active.realizedVolatility20D)}</strong><small>Annualized close-to-close</small></div><div><span>IV premium</span><strong className={tone(active.impliedRealizedSpread)}>{signedPct(active.impliedRealizedSpread)}</strong><small>Implied less realized</small></div><div><span>Expected move</span><strong>{formatPct(active.expectedMove30D)}</strong><small>Nearest 30D tenor</small></div></section>
    <section className="options-grid"><article className="panel chart-panel"><PanelHeader title={`${active.ticker} volatility term structure`} note="ATM and 5% wings / annualized implied volatility" /><div className="chart-body">{terms.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={terms} margin={{ top: 16, right: 10, bottom: 4, left: 0 }}><CartesianGrid vertical={false} stroke="#e2e7e3" /><XAxis dataKey="daysToExpiration" unit="d" tick={{ fill: "#68746d", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis unit="%" width={48} tick={{ fill: "#68746d", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value, name) => [`${Number(value).toFixed(1)}%`, name]} labelFormatter={(value) => `${value} days`} contentStyle={{ border: "1px solid #c9d2cb", borderRadius: 3, fontSize: 11 }} /><Legend iconType="line" wrapperStyle={{ fontSize: 9 }} /><Line dataKey="atm" name="ATM IV" stroke="#3975a7" strokeWidth={2} dot isAnimationActive={false} /><Line dataKey="put" name="95% put IV" stroke="#b8493e" strokeWidth={2} dot isAnimationActive={false} /><Line dataKey="call" name="105% call IV" stroke="#347b57" strokeWidth={2} dot isAnimationActive={false} /></LineChart></ResponsiveContainer> : <div className="chart-empty">Term structure unavailable for this snapshot</div>}</div></article>
      <article className="panel chart-panel"><PanelHeader title="Move pricing by expiration" note="Volatility-model move versus ATM straddle premium / spot" /><div className="chart-body">{terms.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={terms} margin={{ top: 16, right: 10, bottom: 4, left: 0 }}><CartesianGrid vertical={false} stroke="#e2e7e3" /><XAxis dataKey="daysToExpiration" unit="d" tick={{ fill: "#68746d", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis unit="%" width={48} tick={{ fill: "#68746d", fontSize: 10 }} axisLine={false} tickLine={false} /><ReferenceLine y={0} stroke="#aab5ad" /><Tooltip formatter={(value, name) => [`${Number(value).toFixed(2)}%`, name]} labelFormatter={(value) => `${value} days`} contentStyle={{ border: "1px solid #c9d2cb", borderRadius: 3, fontSize: 11 }} /><Legend iconType="square" wrapperStyle={{ fontSize: 9 }} /><Bar dataKey="expectedMove" name="Model move" fill="#3975a7" isAnimationActive={false} /><Bar dataKey="straddleMove" name="Straddle / spot" fill="#b2832e" isAnimationActive={false} /></BarChart></ResponsiveContainer> : <div className="chart-empty">Move pricing unavailable for this snapshot</div>}</div></article></section>
    <article className="panel options-table"><PanelHeader title="Options signal matrix" note="Nearest 30-day tenor / every column is sortable" /><div className="table-scroll"><table><thead><tr>{columns.map(([key, label]) => <th key={key}><button type="button" className={sortKey === key ? "is-sorted" : ""} onClick={() => sort(key)}>{label}{sortKey === key && (direction === "asc" ? <ArrowUp size={11} /> : <ArrowDown size={11} />)}</button></th>)}</tr></thead><tbody>{sorted.map((row) => <tr key={row.ticker} className={row.ticker === active.ticker ? "is-active" : ""}><th><button type="button" className="option-ticker-button" onClick={() => setTicker(row.ticker)}>{row.ticker}</button></th><td>{row.asOf ?? series?.asOf ?? "--"}</td><td>{price(row.spot)}</td><td>{formatIV(row.atmIv30D)}</td><td>{formatPct(row.realizedVolatility20D)}</td><td className={tone(row.impliedRealizedSpread)}>{signedPct(row.impliedRealizedSpread)}</td><td className={tone(row.skew30D)}>{signedPct(row.skew30D)}</td><td>{formatPct(row.expectedMove30D)}</td></tr>)}</tbody></table></div></article>
    <div className="method-note"><strong>Options basis</strong><span>ThetaData v3, last completed session, one-hour IV history and bounded strikes around spot. ATM IV averages call and put mid IV; wings use strikes nearest 95% and 105% moneyness; model move is ATM IV times square root of time. This is a market-pricing diagnostic, not a return forecast.</span></div>
  </>;
}

function sortRows(rows: OptionSnapshot[], key: SortKey, direction: "asc" | "desc") { const sign = direction === "asc" ? 1 : -1; return [...rows].sort((a, b) => { const left = a[key]; const right = b[key]; if (typeof left === "number" && typeof right === "number") return sign * (left - right); if (left === undefined) return 1; if (right === undefined) return -1; return sign * String(left).localeCompare(String(right)); }); }
function percentIV(value?: number) { return value === undefined ? undefined : value * 100; }
function formatIV(value?: number) { return value === undefined ? "--" : `${(value * 100).toFixed(1)}%`; }
function formatPct(value?: number) { return value === undefined ? "--" : `${value.toFixed(1)}%`; }
function signedPct(value?: number) { return value === undefined ? "--" : `${value > 0 ? "+" : ""}${value.toFixed(1)}pp`; }
function price(value?: number) { return value === undefined ? "--" : `$${value.toFixed(value >= 100 ? 0 : 2)}`; }
function tone(value?: number) { return value === undefined ? "" : value >= 0 ? "positive" : "negative"; }
